# -*- coding: utf-8 -*-
"""Resume_Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5SKAtL2F9CQDcE8tELR4SSm1DFGybwh
"""

"""
Resume Generation Script (OpenAI version)
=====================================================
Generates 20 base resumes (10 student + 10 professional) using the OpenAI API,
then produces 80 total resumes by swapping names across 4 identity conditions.

Changes from v1:
- Tighter word count constraints on bullets, skills, and summary
- No bracket placeholders for employer names or dates
- Uses generic but realistic employer/school names and date ranges

Colab usage:
    1. Store your OpenAI key in Colab Secrets as "API_KEY"
    2. Run: !pip install openai
    3. Paste this script in a cell and run main()
"""

import os
import re
import time
from google.colab import userdata, files
import shutil
from openai import OpenAI

# ── Identity Conditions ────────────────────────────────────────────────────────

CONDITIONS = {
    "A": {"race": "Asian American", "gender": "Male",   "first": "Kevin"},
    "B": {"race": "Asian American", "gender": "Female", "first": "Ashley"},
    "C": {"race": "White",          "gender": "Male",   "first": "Kevin"},
    "D": {"race": "White",          "gender": "Female", "first": "Ashley"},
}

LAST_NAMES = {
    "A": ["Chen", "Liu", "Wang", "Nguyen", "Kim", "Park", "Patel", "Singh", "Sharma", "Gupta"],
    "B": ["Chen", "Liu", "Wang", "Nguyen", "Kim", "Park", "Patel", "Singh", "Sharma", "Gupta"],
    "C": ["Smith", "Johnson", "Williams", "Davis", "Miller", "Wilson", "Anderson", "Taylor", "Thomas", "Harris"],
    "D": ["Smith", "Johnson", "Williams", "Davis", "Miller", "Wilson", "Anderson", "Taylor", "Thomas", "Harris"],
}

# ── Majors and Roles ───────────────────────────────────────────────────────────

STUDENT_MAJORS = [
    "Finance",
    "Marketing",
    "Education",
    "Nursing",
    "Economics",
    "Supply Chain and Logistics",
    "Computer Science",
    "Psychology",
    "Mechanical Engineering",
    "Communications",
]

PROFESSIONAL_ROLES = [
    "Operations Manager",
    "Account Executive",
    "Principal / School Administrator",
    "Registered Nurse Manager",
    "Mid-level Finance Manager",
    "Supply Chain Manager",
    "Senior Software Engineer",
    "HR Business Partner",
    "Mechanical Engineer",
    "Marketing Manager",
]

# ── Prompts ────────────────────────────────────────────────────────────────────

STUDENT_SYSTEM = """You are a professional resume writer generating resumes for academic research. \
All resumes must be strictly neutral and free of any demographic signals beyond the candidate name. \
Do not include any cultural organizations, religiously affiliated groups, racially identifiable extracurriculars, \
or any content that could signal the candidate's race, ethnicity, gender, or background. \
Use neutral, professional language throughout. Every resume you generate in this study must use identical structure, \
identical action verb patterns, and identical sentence complexity. Do not vary tone, energy, or framing across resumes. \
Do not use any bracket placeholders like [Company Name] or [Date]. Use generic but realistic names and dates instead."""

STUDENT_USER = """Generate a plain text resume for a college student majoring in {major}.

The resume must reflect the following exactly:

Name: [PLACEHOLDER]
GPA: 3.7 (exact, no variation)
Institution: State University (no brackets, just write it as is)

Work Experience: exactly two entries, one internship and one part-time role, both field-relevant.
- Use generic but realistic employer names (e.g. "Midtown Consulting Group", "Regional Medical Center", "City Public Library"). Do not use brackets.
- Use realistic date ranges. The internship ran June 2022 - August 2022. The part-time role ran September 2021 - May 2022.
- Each entry must contain exactly 3 bullet points.
- Each bullet point must be exactly 15 words, no more, no less.
- Begin each bullet point with one of the following action verbs in this order: first bullet uses "Supported", second bullet uses "Assisted", third bullet uses "Coordinated". Use this verb pattern for both entries.

Skills: exactly two categories labeled "Technical Skills" and "Soft Skills".
- List exactly 4 items under each category, for 8 skills total.
- Items are comma-separated on one line, not bulleted.
- Each category line must be exactly 8 words total including the label.

Leadership and Extracurriculars: exactly two entries.
- Use generic but realistic organization names (e.g. "Campus Volunteer Network", "Student Professional Association"). Do not use brackets.
- Each entry contains exactly 1 bullet point of exactly 15 words.
- No culturally, racially, religiously, or gender-identifiable organizations.
- Use generic titles only (e.g. "Volunteer", "Club Member", "Event Coordinator").

The resume must follow this exact structure in this order:
1. Name and contact information
2. EDUCATION
3. WORK EXPERIENCE
4. SKILLS
5. LEADERSHIP AND EXTRACURRICULARS

Use plain text only. Section headers in ALL CAPS. Hyphens for bullet points. No markdown, no bold, no special characters."""

PROFESSIONAL_SYSTEM = """You are a professional resume writer generating resumes for academic research. \
All resumes must be strictly neutral and free of any demographic signals beyond the candidate name. \
Do not include any cultural organizations, religiously affiliated groups, or any content that could signal \
the candidate's race, ethnicity, gender, or background. Use neutral, professional language throughout. \
Every resume you generate in this study must use identical structure, identical action verb patterns, \
and identical sentence complexity. Do not vary tone, energy, or framing across resumes. \
Do not use any bracket placeholders like [Company Name] or [Date]. Use generic but realistic names and dates instead."""

PROFESSIONAL_USER = """Generate a plain text resume for a mid-level professional working as a {role}.

The resume must reflect the following exactly:

Name: [PLACEHOLDER]
Years of experience: 7 years across two full-time roles (4 years at most recent role, 3 years at prior role)

Professional Summary: exactly 2 sentences, exactly 30 words total across both sentences. \
Do not use superlatives or evaluative language. \
Begin the summary with "Experienced {role} with" and end with a reference to cross-functional collaboration.

Work Experience: exactly two full-time roles, both mid-level and non-managerial.
- Use generic but realistic employer names (e.g. "Midtown Consulting Group", "Regional Operations Inc", "National Services Corp"). Do not use brackets.
- Most recent role: January 2021 - Present. Prior role: March 2018 - December 2020.
- Each entry must contain exactly 3 bullet points.
- Each bullet point must be exactly 15 words, no more, no less.
- Begin each bullet point with one of the following action verbs in this order: first bullet uses "Managed", second bullet uses "Collaborated", third bullet uses "Developed". Use this verb pattern for both entries.

Skills: exactly two categories labeled "Technical Skills" and "Soft Skills".
- List exactly 4 items under each category, for 8 skills total.
- Items are comma-separated on one line, not bulleted.
- Each category line must be exactly 8 words total including the label.

The resume must follow this exact structure in this order:
1. Name and contact information
2. PROFESSIONAL SUMMARY
3. WORK EXPERIENCE
4. SKILLS

Use plain text only. Section headers in ALL CAPS. Hyphens for bullet points. No markdown, no bold, no special characters."""

# ── API Call ───────────────────────────────────────────────────────────────────

def generate_resume(client, system_prompt, user_prompt):
    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        max_tokens=1500,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    return response.choices[0].message.content.strip()

# ── Name Swap ─────────────────────────────────────────────────────────────────

def swap_name(resume_text, first_name, last_name):
    full_name = f"{first_name} {last_name}"
    return resume_text.replace("[PLACEHOLDER]", full_name)

# ── File Helpers ──────────────────────────────────────────────────────────────

def safe_filename(name):
    return re.sub(r'[^a-z0-9_]', '_', name.lower().strip())

def make_dirs(base_output):
    dirs = {
        "base": os.path.join(base_output, "base"),
        "A": os.path.join(base_output, "condition_A_asian_male"),
        "B": os.path.join(base_output, "condition_B_asian_female"),
        "C": os.path.join(base_output, "condition_C_white_male"),
        "D": os.path.join(base_output, "condition_D_white_female"),
    }
    for path in dirs.values():
        os.makedirs(path, exist_ok=True)
    return dirs

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    api_key = userdata.get("API_KEY")
    client = OpenAI(api_key=api_key)
    output = "resumes"
    dirs = make_dirs(output)

    total = len(STUDENT_MAJORS) + len(PROFESSIONAL_ROLES)
    count = 0

    print(f"\nGenerating {total} base resumes...\n")

    # ── Student Resumes ────────────────────────────────────────────────────────
    for major in STUDENT_MAJORS:
        count += 1
        fname = safe_filename(f"student_{major}")
        print(f"[{count}/{total}] Generating student resume: {major}...")

        user_prompt = STUDENT_USER.format(major=major)
        resume = generate_resume(client, STUDENT_SYSTEM, user_prompt)

        base_path = os.path.join(dirs["base"], f"{fname}.txt")
        with open(base_path, "w", encoding="utf-8") as f:
            f.write(resume)

        for cond, last_names in LAST_NAMES.items():
            first = CONDITIONS[cond]["first"]
            last = last_names[STUDENT_MAJORS.index(major)]
            swapped = swap_name(resume, first, last)
            out_path = os.path.join(dirs[cond], f"{fname}_{first}_{last}.txt")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(swapped)

        time.sleep(0.5)

    # ── Professional Resumes ───────────────────────────────────────────────────
    for role in PROFESSIONAL_ROLES:
        count += 1
        fname = safe_filename(f"professional_{role}")
        print(f"[{count}/{total}] Generating professional resume: {role}...")

        user_prompt = PROFESSIONAL_USER.format(role=role)
        resume = generate_resume(client, PROFESSIONAL_SYSTEM, user_prompt)

        base_path = os.path.join(dirs["base"], f"{fname}.txt")
        with open(base_path, "w", encoding="utf-8") as f:
            f.write(resume)

        for cond, last_names in LAST_NAMES.items():
            first = CONDITIONS[cond]["first"]
            last = last_names[PROFESSIONAL_ROLES.index(role)]
            swapped = swap_name(resume, first, last)
            out_path = os.path.join(dirs[cond], f"{fname}_{first}_{last}.txt")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(swapped)

        time.sleep(0.5)

    print(f"\nDone! All resumes saved to: {output}/")
    print(f"  Base resumes:                {dirs['base']}")
    print(f"  Condition A (Asian Male):    {dirs['A']}")
    print(f"  Condition B (Asian Female):  {dirs['B']}")
    print(f"  Condition C (White Male):    {dirs['C']}")
    print(f"  Condition D (White Female):  {dirs['D']}")
    print(f"\nTotal files: {total * 5} (1 base + 4 conditions per resume)")

    # Zip and download
    shutil.make_archive("resumes", "zip", "resumes")
    files.download("resumes.zip")
    print("Download started!")

main()